### PR TITLE
New recipe seeds

### PR DESCRIPTION
**Pull request by jondedman**
I have made some more api calls to ppopulate JSONS with vegetarian, vegan, dairy free and gluten fee recipes. Please re-seed after merging.

### CODE REVIEW

**Comment by jondedman** [comment]
Hi guys, in the last commit, i also updated the show page so it would not display any numbers in the name of the ingredient. I've just thought it is probably better not to store the ingredients in the database like this in the first place. I will figure out how to use the helper method i created at the seeding stage.

**Comment by jondedman** [comment]
The seed file now removes integers present in the ingredient name (nor recipe name as in the commit title). It also ensures that, after the html tags are stripped from the code, a white space is placed after any full-stops.

**Comment by fransan6** [comment]
Great, thanks so much!

It looks like you have defined `remove_integer()` in two places so I think you should remove one? You may not even need the method as instead of `remove_integer(api_ingredient[:name])`, you could have `api_ingredient[:name].gsub(/\d+/, '').strip`, or did that not work?

Also, perhaps I'm missing something but why has `.capitalize` been removed from the seed file and added back to the show?

And so numbers where present in ingredient names? I'm a bit confused as I didn't see any numbers in the list of ingredient names - do you have an example as I'm missing something, sorry! I'm envisioning something like 'Bana9na' :')

**Comment by jondedman** [comment]
Hi Fran, thanks for this.

Unfortunately, the name of the ingredients sometimes included an integer - which led to things on the show page like "1 1 lemon". So i thought it best to get rid of this as the quantity_amount is specified elsewhere. I only noticed it once the vegetarian recipes were seeded.

The remove_integer helper method could be removed as it's no longer being used in the show. Having the method outside the main seeding make that line a bit shorter. It might work to just add it on the end of the line as you suggest though. I think i had some trouble with this to start with. However, the seed file is getting a bit unwieldy, so could probably be refactored at some point. perhaps some of the other checks etc could be extrapolated outside as well.

I got rid of the capitalisation of the ingredient name when seeding because i thought it would make it easier when we are trying to reduce duplicate db ingredients. Otherwise, If you do a comparison, then you have to capitalise the name of each ingredient before checking it against the db. This seemed like it might take a while with a larger dataset. On the show page it only has to capitalize a few times.

**Comment by fransan6** [comment]
Cool, thanks a lot for explaining! That's odd there are numbers in ingredients you see.. in Ilaria and Alessandro's dropdown that lists all ingredients, there are no numbers (apart from two that include a measurement). Maybe if I re-seeded, it would change - you just got ingredients with integers.

I'm not sure if it would be better to capitalise the seed as then we have to manually capitalise ingredients on show, user-added ingredients on profile, during any logic that compares the two and I'm not sure if the dropdown on the profile page would then have some ingredients capitalised and some not? Not sure how we'd work around the dropdown one?

**Comment by jondedman** [comment]
No worries, Fran. Yes, i only noticed this once i added in vegetarian recipes to the seed. BTW the seed file currently works by looping over each of the JSONs of data, then checks to see if the recipe exists before seeding it to the database. We could expand this by adding further JSONs of data from elsewhere, or change a few things if we wanted to scrape data from elsewhere. 

I see your point about the dropdown. I can add this functionality back in to the seed file, so we are seeding capitalised then comparing. This will avoid funny logic later on.

**Comment by jondedman** [comment]
I have updated as you suggested Fran.

**Pull request merged**
