### PR TITLE
generate migration file

### PR DESCRIPTION
**Pull request by jondedman**
Hi guys, i have generated a migration file to add bio, image_url and diet to users, and updated the seed file accordingly. The images are random faces from unsplash. Note there is no logic for generating a gendered picture, but i'm not sure that matters. We are using usernames anyway. We can also hard code these if we want for which ever user we would use in the demo.

### CODE REVIEW

**Comment by fransan6** [comment]
Thanks! Can't see the seed file changes though?

**Comment by jondedman** [comment]
I must have not pushed. It is there now

**Comment by fransan6** [comment]
LGTM!

**Comment by alexagodzilla** [comment]
LGTM too

**Pull request merged**
