### PR TITLE
fix footer on pages with less content

### PR DESCRIPTION
**Pull request by jondedman**
Hi guys, i have fixed this issue by setting the body of our website to be a flex-box and then making the footer have a margin-top that takes up any remaining space on a page with little content like the profile page. I have pasted the solution on our slack channel as well in case that is useful. In addition, I also altered the spacing around the banner as i though it looked a bit too much. Feel free to change it back though if you want.
Screenshot 2023-03-12 at 22 34 32
Screenshot 2023-03-12 at 22 35 00

### CODE REVIEW

**Comment by fransan6** [comment]
Thanks so much! Is there anyway to have some margin above the footer so the content, as shown on the index, isn't super close to the body content?

**Comment by jondedman** [comment]
Thanks Fran. Yes, i believe we could increase this by adding some margin bottom to the body. However, i think it looks ok now that you have moved the buttons for the filter?
Screenshot 2023-03-13 at 13 56 12

**Comment by fransan6** [comment]
Thanks a lot! We all had a look and think the top of the footer should have some more margin - is that OK?

**Comment by jondedman** [comment]
Screenshot 2023-03-14 at 00 46 53
Hi guys, i have increased the min vh of the body from 100 to 105 which creates more space between the bottom of the page and the footer. This should be more evident once merged with the code that has moved the buttons.

**Comment by jondedman** [comment]
Screenshot 2023-03-14 at 01 17 26

How about this? We can make it less gap - 116/110?? I think the buttons for the sorting filter still need styling and the color of the footer changing. However, i think these should be covered in another branch.

**Comment by alexagodzilla** [comment]
LGTM

**Pull request merged**
