### PR TITLE
create test data file

### PR DESCRIPTION
**Pull request by jondedman**
test hash of recipes for reference created

### CODE REVIEW

**Comment by fransan6** [comment]
Thanks a lot for this!

**Comment by fransan6** [comment]
Great, thanks so much!

What do you think about Review ratings as 3..5 instead of 1..5? For Pay n Play, we went for 3..5 otherwise some of the venues had really low ratings.

Do you think we will we log in as any of these Users? If so, perhaps we should keep a set password for each of them, so we know how to log in as a generated User.

**Comment by jondedman** [comment]
Thanks Fran, as mentioned i have updated the ratings to seed with 3..5 stars for more realistic reviews. I think we can keep the seeded users passwords as unique and sign-up as a user when we are testing. But it's easy to change locally if you want to try signing in as different users.

**Comment by fransan6** [comment]
OK great, thanks! 
I've added `total_time` to the Recipe model so think you might need to change lines 41-43 in the seed file then all good to go? 

I may have misunderstood on Slack though. Are we populating `prep_time`,` cooking_time` and `total_time` (total_time being the readyInMinutes), or are we just populating total_time? I have the model validations set up as if there will only be a total_time.

**Comment by jondedman** [comment]
Cool. I think we can leave prep-time and cooking-time in for now but don't enforce them through validations at this stage. If we have them there, then we have the option to play around with them as we develop features as needed. We can remove them again at a later stage. I vote keep them in. What do you think? I will merge your PR before you merge mine, just to make sure that the seeds and validations etc are working in sync.

**Comment by jondedman** [comment]
Actually, I'll just merge yours validations and associations as they are. We can always revisit prep time and cooking time later if we want to play with them. Thanks Fran.

**Comment by fransan6** [comment]
OK! But we will populate `total_time` from the seed file?

**Pull request merged**
